### ISSUE TITLE
UDM/UDM Pro

### ISSUE THREAD

**Issue by flowmymind** [fernwerker/ownDynDNS#15]
Hi. 

Does anybody use ownDynDNS with an UDM/UDM Pro? Ubiquitis DDNS update does not work well. Some information about it:

[English 1](https://dixonwille.medium.com/custom-dynamic-dns-with-unifi-dream-machine-pro-b664f7c964) 
[German 1](https://ichi.pro/de/benutzerdefiniertes-dynamisches-dns-mit-unifi-dream-machine-pro-783378008420) 
[German 2](https://ubiquiti-networks-forum.de/wiki/entry/35-dyndns-mit-der-udm-pro-base/) 
[UI community (english)](https://community.ui.com/questions/UDM-DynDNS-Google-Domains/fe9ba35d-66c3-437d-8323-debe2af55879#answer/2181146e-79b8-485c-8042-eb975c291242)

I have tried some URL, but it won’t work.

**Comment by fernwerker** [comment]
Did you check if everything is working fine by doing an HTTP post by yourself.
So see if you have everything in place and DNS entries are able to update.

Afterwards I'd check on the UDM side again.
The script is designed for Fritzbox, but the HTTP post is generic and therefore can be done by any client.

**Comment by flowmymind** [comment]
So i run a test on [https://webhook.site](url) with these UDM settings:

Hostname: my.uniq.hostname
Username: myuniqusername
Password: myuniqpassword
Server: webhook.site/12db0813-255a-4915-b497-a746517f7ccb/\/nic/update?user=%u&password=%p&ipv4=%i&force=0&mode=both&domain=

Everything looks ok. It is a GET method. All query strings (name & value) are correct. Yes, the domain value is blank, so it is with the first request. But after the first request the UDM script puts the hostname to the last value (no matter which one is the last). So with the second request everything is right. Also php-auth-user and php-auth-pw were correct. So I run a similar request to my own server, just replaced hostname, username and password and changed the serveradress to: mysub.domain.com/ownDynDNS/update.php\/nic/update?... but the ownDynDNS log has not been written.

**Comment by flowmymind** [comment]
So i run a test on https://webhook.site with these UDM settings:

Hostname: mysub.mydomain.com
Username: myuniqusername
Password: myuniqpassword
Server: webhook.site/mywebhook/\/nic/update?user=%u&password=%p&ipv4=%i&force=0&mode=both&domain=

Everything looks ok. It is a GET method. All query strings (name & value) are correct. Yes, the domain value is blank, so it is with the first request. But after the first request the UDM script puts the hostname to the last value (no matter which one is the last). So with the second request everything is right. Also php-auth-user and php-auth-pw were correct. So I run a similar request to my own server, just replaced hostname, username and password and changed the serveradress to: mydomain.com/ownDynDNS/update.php/nic/update?... but the ownDynDNS log has not been written.
Log of inadyn says:

inadyn[17945]: Unknown format specifier in ddns-path: '&'
inadyn[17945]: Invalid server URL: /ownDynDNS/update.php//nic/update?user= myuniqusername&password= myuniqpassword&ipv4=%&force=0&mode=bothi&domain=%h
inadyn[17945]: Sending alias table update to DDNS server: GET /ownDynDNS/update.php//nic/update?user= myuniqusername&password= myuniqpassword&ipv4=%25&force=0&mode=bothi&domain=%25h HTTP/1.0
Host: bettervetter.de
Authorization: Basic ZmxvcmlhbnZldHRlcjpkc3lyUUcxbFZaNm8=
User-Agent: inadyn/2.5 https://github.com/troglobit/inadyn/issues

inadyn[17945]: Sending IP# update to DDNS server, initiating HTTPS ...
inadyn[17945]: SSL connection using ECDHE-RSA-AES128-GCM-SHA256
inadyn[17945]: Certificate OK
inadyn[17945]: SSL server cert subject: /CN=mydomain.com
inadyn[17945]: SSL server cert issuer: /C=US/O=Let's Encrypt/CN=R3
inadyn[17945]: Unknown format specifier in ddns-path: '&'
inadyn[17945]: Invalid server URL: /ownDynDNS/update.php//nic/update?user= myuniqusername&password=dsyrQG1lVZ6o&myunipassword&ipv4=%&force=0&mode=bothi&domain=%h
inadyn[17945]: Sending alias table update to DDNS server: GET /ownDynDNS/update.php//nic/update?user=myuniqusername&password=dsyrQG1lVZ6o&myunipassword&ipv4=%25&force=0&mode=bothi&domain=%25h HTTP/1.0
Host: mydomain.com
Authorization: Basic ZmxvcmlhbnZldHRlcjpkc3lyUUcxbFZaNm8=
User-Agent: inadyn/2.5 https://github.com/troglobit/inadyn/issues

inadyn[17945]: Successfully sent HTTPS request!
inadyn[17945]: Successfully received HTTPS response (597 bytes)!
inadyn[17945]: DDNS server response: HTTP/1.1 200 OK
Server: nginx
Date: Mon, 10 May 2021 09:53:42 GMT
Content-Type: text/plain; charset=utf-8
Connection: close
Vary: Accept-Encoding
Vary: Accept-Encoding

Fatal error: Uncaught RuntimeException: payload invalid in .../ownDynDNS/src/Handler.php:35
Stack trace:
#0 .../ownDynDNS/update.php(20): netcup\DNS\API\Handler->__construct(Array, Array)
#1 {main}
thrown in .../ownDynDNS/src/Handler.php on line 35
inadyn[17945]: Fatal error in DDNS server response:
inadyn[17945]: [200 OK]
Fatal error: Uncaught RuntimeException: payload invalid in .../ownDynDNS/src/Handler.php:35
Stack trace:
#0 .../ownDynDNS/update.php(20): netcup\DNS\API\Handler->__construct(Array, Array)
#1 {main}
thrown in .../ownDynDNS/src/Handler.php on line 35
inadyn[17945]: Error response from DDNS server, ignoring ...

so payload is invalid? same response when I add %h to &domain=

**Comment by flowmymind** [comment]
So i run a test on https://webhook.site with these UDM settings:

Hostname: mysub.mydomain.com
Username: myuniqusername
Password: myuniqpassword
Server: webhook.site/mywebhook/\/nic/update?user=%u&password=%p&ipv4=%i&force=0&mode=both&domain=

Everything looks ok. It is a GET method. All query strings (name & value) are correct. Yes, the domain value is blank, so it is with the first request. But after the first request the UDM script puts the hostname to the last value (no matter which one is the last). So with the second request everything is right. Also php-auth-user and php-auth-pw were correct. So I run a similar request to my own server, just replaced hostname, username and password and changed the serveradress to: mydomain.com/ownDynDNS/update.php/nic/update?... but the ownDynDNS log has not been written.
Log of inadyn says:

inadyn[17945]: Unknown format specifier in ddns-path: '&'
inadyn[17945]: Invalid server URL: /ownDynDNS/update.php//nic/update?user= myuniqusername&password= myuniqpassword&ipv4=%&force=0&mode=bothi&domain=%h
inadyn[17945]: Sending alias table update to DDNS server: GET /ownDynDNS/update.php//nic/update?user= myuniqusername&password= myuniqpassword&ipv4=%25&force=0&mode=bothi&domain=%25h HTTP/1.0
Host: mydomain.com
Authorization: Basic ZmxvcmlhbnZldHRlcjpkc3lyUUcxbFZaNm8=
User-Agent: inadyn/2.5 https://github.com/troglobit/inadyn/issues

inadyn[17945]: Sending IP# update to DDNS server, initiating HTTPS ...
inadyn[17945]: SSL connection using ECDHE-RSA-AES128-GCM-SHA256
inadyn[17945]: Certificate OK
inadyn[17945]: SSL server cert subject: /CN=mydomain.com
inadyn[17945]: SSL server cert issuer: /C=US/O=Let's Encrypt/CN=R3
inadyn[17945]: Unknown format specifier in ddns-path: '&'
inadyn[17945]: Invalid server URL: /ownDynDNS/update.php//nic/update?user= myuniqusername&password=dsyrQG1lVZ6o&myunipassword&ipv4=%&force=0&mode=bothi&domain=%h
inadyn[17945]: Sending alias table update to DDNS server: GET /ownDynDNS/update.php//nic/update?user=myuniqusername&password=dsyrQG1lVZ6o&myunipassword&ipv4=%25&force=0&mode=bothi&domain=%25h HTTP/1.0
Host: mydomain.com
Authorization: Basic ZmxvcmlhbnZldHRlcjpkc3lyUUcxbFZaNm8=
User-Agent: inadyn/2.5 https://github.com/troglobit/inadyn/issues

inadyn[17945]: Successfully sent HTTPS request!
inadyn[17945]: Successfully received HTTPS response (597 bytes)!
inadyn[17945]: DDNS server response: HTTP/1.1 200 OK
Server: nginx
Date: Mon, 10 May 2021 09:53:42 GMT
Content-Type: text/plain; charset=utf-8
Connection: close
Vary: Accept-Encoding
Vary: Accept-Encoding

Fatal error: Uncaught RuntimeException: payload invalid in .../ownDynDNS/src/Handler.php:35
Stack trace:
#0 .../ownDynDNS/update.php(20): netcup\DNS\API\Handler->__construct(Array, Array)
#1 {main}
thrown in .../ownDynDNS/src/Handler.php on line 35
inadyn[17945]: Fatal error in DDNS server response:
inadyn[17945]: [200 OK]
Fatal error: Uncaught RuntimeException: payload invalid in .../ownDynDNS/src/Handler.php:35
Stack trace:
#0 .../ownDynDNS/update.php(20): netcup\DNS\API\Handler->__construct(Array, Array)
#1 {main}
thrown in .../ownDynDNS/src/Handler.php on line 35
inadyn[17945]: Error response from DDNS server, ignoring ...

so payload is invalid? same response when I add %h to &domain=

**Comment by flowmymind** [comment]
So i run a test on https://webhook.site with these UDM settings:
Hostname: mysub.mydomain.com
Username: myuniqusername
Password: myuniqpassword
Server: webhook.site/mywebhook//nic/update?user=%u&password=%p&ipv4=%i&force=0&mode=both&domain=
Everything looks ok. It is a GET method. All query strings (name & value) are correct. Yes, the domain value is blank, so it is with the first request. But after the first request the UDM script puts the hostname to the last value (no matter which one is the last). So with the second request everything is right. Also php-auth-user and php-auth-pw were correct. So I run a similar request to my own server, just replaced hostname, username and password and changed the serveradress to: mydomain.com/ownDynDNS/update.php/nic/update?... but the ownDynDNS log has not been written.
Log of inadyn says:
inadyn[17945]: Unknown format specifier in ddns-path: '&'
inadyn[17945]: Invalid server URL: /ownDynDNS/update.php//nic/update?user= myuniqusername&password= myuniqpassword&ipv4=%&force=0&mode=bothi&domain=%h
inadyn[17945]: Sending alias table update to DDNS server: GET /ownDynDNS/update.php//nic/update?user= myuniqusername&password= myuniqpassword&ipv4=%25&force=0&mode=bothi&domain=%25h HTTP/1.0
Host: mydomain.com
Authorization: Basic ZmxvcmlhbnZldHRlcjpkc3lyUUcxbFZaNm8=
User-Agent: inadyn/2.5 https://github.com/troglobit/inadyn/issues
inadyn[17945]: Sending IP# update to DDNS server, initiating HTTPS ...
inadyn[17945]: SSL connection using ECDHE-RSA-AES128-GCM-SHA256
inadyn[17945]: Certificate OK
inadyn[17945]: SSL server cert subject: /CN=mydomain.com
inadyn[17945]: SSL server cert issuer: /C=US/O=Let's Encrypt/CN=R3
inadyn[17945]: Unknown format specifier in ddns-path: '&'
inadyn[17945]: Invalid server URL: /ownDynDNS/update.php//nic/update?user= myuniqusername&password=myuniqpassword&ipv4=%&force=0&mode=bothi&domain=%h
inadyn[17945]: Sending alias table update to DDNS server: GET /ownDynDNS/update.php//nic/update?user=myuniqusername&password=myuniqpassword&ipv4=%25&force=0&mode=bothi&domain=%25h HTTP/1.0
Host: mydomain.com
Authorization: Basic ZmxvcmlhbnZldHRlcjpkc3lyUUcxbFZaNm8=
User-Agent: inadyn/2.5 https://github.com/troglobit/inadyn/issues
inadyn[17945]: Successfully sent HTTPS request!
inadyn[17945]: Successfully received HTTPS response (597 bytes)!
inadyn[17945]: DDNS server response: HTTP/1.1 200 OK
Server: nginx
Date: Mon, 10 May 2021 09:53:42 GMT
Content-Type: text/plain; charset=utf-8
Connection: close
Vary: Accept-Encoding
Vary: Accept-Encoding
Fatal error: Uncaught RuntimeException: payload invalid in .../ownDynDNS/src/Handler.php:35
Stack trace:
#0 .../ownDynDNS/update.php(20): netcup\DNS\API\Handler->__construct(Array, Array)
#1 {main}
thrown in .../ownDynDNS/src/Handler.php on line 35
inadyn[17945]: Fatal error in DDNS server response:
inadyn[17945]: [200 OK]
Fatal error: Uncaught RuntimeException: payload invalid in .../ownDynDNS/src/Handler.php:35
Stack trace:
#0 .../ownDynDNS/update.php(20): netcup\DNS\API\Handler->__construct(Array, Array)
#1 {main}
thrown in .../ownDynDNS/src/Handler.php on line 35
inadyn[17945]: Error response from DDNS server, ignoring ...
so payload is invalid? same response when I add %h to &domain=

**Comment by flowmymind** [comment]
After lots of testing it works!

Settings for UDM:

Interface: WAN (or your choice)
Service: dyndns (but actually not matter because inadyn runs it own script if "Server" is filled)
Hostname: dnssub.domain.com
Username: ownDynDNS username
Password: ownDynDNS password
Server: **domain.com/ownDynDNS/update.php**/\/nic/update?user=%u&password=%p&ipv4=%i&force=0&mode=both&domain=%h

Attention: save ownDynDNS not on your dnssub.domain.com, but on domain.com or another sub.domain.com.
